# Site settings
title: Digital Rain using Modern C++ and Recursion

author:
  name: Shannon Fernandes
  email: your-email@domain.com
description: "My C++ project page"

# Build settings
remote_theme: just-the-docs

plugins:
- jekyll-remote-theme
